// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Sentiment_analysis_console_app
{
    public partial class SentimentAnalysis
    {
        /// <summary>
        /// model input class for SentimentAnalysis.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"id")]
            public string Id { get; set; }

            [ColumnName(@"comment_text")]
            public string Comment_text { get; set; }

            [ColumnName(@"toxic")]
            public float Toxic { get; set; }

            [ColumnName(@"severe_toxic")]
            public float Severe_toxic { get; set; }

            [ColumnName(@"obscene")]
            public float Obscene { get; set; }

            [ColumnName(@"threat")]
            public float Threat { get; set; }

            [ColumnName(@"insult")]
            public float Insult { get; set; }

            [ColumnName(@"identity_hate")]
            public float Identity_hate { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentimentAnalysis.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"id")]
            public float[] Id { get; set; }

            [ColumnName(@"comment_text")]
            public float[] Comment_text { get; set; }

            [ColumnName(@"toxic")]
            public uint Toxic { get; set; }

            [ColumnName(@"severe_toxic")]
            public float Severe_toxic { get; set; }

            [ColumnName(@"obscene")]
            public float Obscene { get; set; }

            [ColumnName(@"threat")]
            public float Threat { get; set; }

            [ColumnName(@"insult")]
            public float Insult { get; set; }

            [ColumnName(@"identity_hate")]
            public float Identity_hate { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentimentAnalysis.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
