﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Sentiment_analysis_console_app
{
    public partial class SentimentAnalysis
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"severe_toxic", @"severe_toxic"),new InputOutputColumnPair(@"obscene", @"obscene"),new InputOutputColumnPair(@"threat", @"threat"),new InputOutputColumnPair(@"insult", @"insult"),new InputOutputColumnPair(@"identity_hate", @"identity_hate")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"id",outputColumnName:@"id"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"comment_text",outputColumnName:@"comment_text"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"severe_toxic",@"obscene",@"threat",@"insult",@"identity_hate",@"id",@"comment_text"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"toxic",inputColumnName:@"toxic"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator: mlContext.BinaryClassification.Trainers.LbfgsLogisticRegression(new LbfgsLogisticRegressionBinaryTrainer.Options(){L1Regularization=0.03125F,L2Regularization=0.03125F,LabelColumnName=@"toxic",FeatureColumnName=@"Features"}), labelColumnName:@"toxic"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
